version: "3.3"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    environment:
      JAEGER_ENDPOINT: "jaeger:4317"
      LOKI_ENDPOINT: "http://loki:3200/loki/api/v1/push"
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    depends_on:
      # - jaeger
      - prometheus
      - loki
  tempo:
    image: grafana/tempo:2.1.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      # - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - 3200:3200   # tempo
      - 4327:4327  # otlp grpc
      - 4328:4328  # otlp http
      - "9411"   # zipkin
  # tempo:
  #   image: grafana/tempo:2.1.1
  #   ports:
  #     - 3100:3100
  #     - 4327:4317
  #     - 4328:4318
    # command: -config.file=/etc/tempo/local-config.yaml
  # jaeger:
  #   image: jaegertracing/all-in-one:1.38.1
  #   environment:
  #     - "COLLECTOR_OTLP_ENABLED=true"
  #   expose:
  #     - "4317"
  #     - "4318"
  #   ports:
  #     - 16686:16686

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:9.5.5
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - prometheus
      # - jaeger

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
